# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Default Multivariate Total Variation Denoising Solver
#' @description Create a mesh and find cross-validated best 
#' approximation to total variation denoising problem. 
#' @name mvtv.default
#' @param data n by p matrix of inputs
#' @param y response column vector
#' @param m vector of number of mesh points per predictor 
#' @param mesh user can supply or NULL for regularly spaced mesh, which will be returned
#' @param n_lambda number of logarithmically spaced tuning parameters
#' @param ftrue prediction target. If NULL, use observed data. 
#' @param lambdas user can supply vector of lambdas to be solved over. If NULL,
#' function generates n_lambda logarithmically spaced lambdas from 0.00001*lambda_max
#' and lambda_max, where lambda_max is our approximation of smallest lambda where
#' regularization ends. 
#' @param folds number of folds for cross-validation
#' @param verbose Default: true, prints out current working penalty and 
#' number of iters to solve.
#' @examples
#' # Approximating Bivariate Fused Lasso for Uniform Data 
#' ## Generate Data
#' set.seed(117)
#' x <- matrix(runif(100),ncol = 2)
#' y <- matrix(runif(50),ncol=1)
#' m <- matrix(c(3,3))
#' 
#' ## Find Total Variation Solution over range of lambdas and whole data set
#' mvtv_fold1 <- mvtv(x,y,m,folds=1, verbose = FALSE)
#' 
#' ## Find 5-fold validated MVTV Model over range of lambdas
#' mvtv_fold5 <- mvtv(x,y,m,folds=5, verbose = FALSE)
#' 
#' @export
mvtv.default <- function(data, y, m, mesh = NULL, n_lambda = 100L, ftrue = NULL, lambdas = NULL, folds = 5L, verbose = TRUE) {
    .Call(`_MultivarTV_mbs`, data, y, m, mesh, n_lambda, ftrue, lambdas, folds, verbose)
}

#' @title MVTV Predict Function
#' @description Use fitted 'mvtv' object to predict new data.
#' @name predict.mvtv
#' @param mvtvobject object produced by mbtv.default
#' @param data n by p matrix of inputs
#' @examples
#' # Approximating Bivariate Fused Lasso for Uniform Data 
#' ## Generate Data
#' set.seed(117)
#' x <- matrix(runif(100),ncol = 2)
#' y <- matrix(runif(50),ncol=1)
#' m <- matrix(c(3,3))
#' 
#' ## Find 5-fold validated MBS Model over range of lambdas
#' mbs_fold5 <- mvtv(x,y,m,folds=5,verbose=FALSE)
#' 
#' # Access fitted values of training data; equivalent to mbs_fold5$fitted
#' fitted.values <- predict(mbs_fold5) 
#' newdata <- matrix( runif(50), ncol = 2) # Generate new data
#' newfits <- predict(mbs_fold5, newdata) # Fit new data
#' @export
predict.mvtv <- function(mvtvobject, data = NULL) {
    .Call(`_MultivarTV_mbspredict`, mvtvobject, data)
}

#' @title Generate a mesh
#' @description Single function to handle creating a mesh regularly
#' across domain of predictors. Mesh created is a convex hull of predictor space. 
#' @name gen_mesh
#' @param data n by p matrix of inputs
#' @param m vector of length p with number of knots desired for each predictor
#' @param mesh NULL; otherwise, takes user defined mesh. 
#' @export
gen_mesh <- function(data, m, mesh) {
    .Call(`_MultivarTV_gen_mesh`, data, m, mesh)
}

