// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mbs
Rcpp::List mbs(arma::mat data, arma::vec y, arma::vec m, Rcpp::Nullable<arma::mat> mesh, int n_lambda, Rcpp::Nullable<arma::vec> ftrue, Rcpp::Nullable<arma::vec> lambdas, int folds, bool verbose);
RcppExport SEXP _MultivarTV_mbs(SEXP dataSEXP, SEXP ySEXP, SEXP mSEXP, SEXP meshSEXP, SEXP n_lambdaSEXP, SEXP ftrueSEXP, SEXP lambdasSEXP, SEXP foldsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< int >::type n_lambda(n_lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type ftrue(ftrueSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< int >::type folds(foldsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(mbs(data, y, m, mesh, n_lambda, ftrue, lambdas, folds, verbose));
    return rcpp_result_gen;
END_RCPP
}
// mbspredict
arma::vec mbspredict(Rcpp::List mvtvobject, Rcpp::Nullable<arma::mat> data, Rcpp::Nullable<arma::mat> mesh);
RcppExport SEXP _MultivarTV_mbspredict(SEXP mvtvobjectSEXP, SEXP dataSEXP, SEXP meshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mvtvobject(mvtvobjectSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type mesh(meshSEXP);
    rcpp_result_gen = Rcpp::wrap(mbspredict(mvtvobject, data, mesh));
    return rcpp_result_gen;
END_RCPP
}
// gen_mesh
arma::mat gen_mesh(arma::mat data, arma::vec m, Rcpp::Nullable<arma::mat> mesh);
RcppExport SEXP _MultivarTV_gen_mesh(SEXP dataSEXP, SEXP mSEXP, SEXP meshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type mesh(meshSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_mesh(data, m, mesh));
    return rcpp_result_gen;
END_RCPP
}
